#
# Default Settings for Flowpack.SingleSignOn.Client
#

Flowpack:
  SingleSignOn:
    # SSO client configuration
    Client:
      client:
        # The client service base URI as the client identifier
        # Must point to the URI where the SSO client routes are mounted
        serviceBaseUri: ''
        # The client key pair fingerprint
        publicKeyFingerprint: ''

      # A list of named SSO server configurations
      server: null
        # Example server configuration
        #
        #   DemoServer:
        #     publicKeyFingerprint: 'bb5abb57faa122cc031e3c904db3d751'
        #     serviceBaseUri: 'http://ssoserver/sso'

      # Map a party type from the server to the instance, more complex scenarios
      # need a specialized account mapper implementation (see GlobalAccountMapperInterface)
      #
      # typeMapping:
      #   'Vendor\MyServer\Domain\Model\SomeParty': 'Vendor\MyApplication\Domain\Model\OtherParty'
      #
      accountMapper:
        typeMapping: {  }
      log:
        # Enable logging of failed signed requests (signature verification errors)
        logFailedSignedRequests: false

# Example configuration for a SSO entry point
#
#   Neos:
#     Flow:
#       security:
#         authentication:
#           providers:
#             SingleSignOnProvider:
#               provider: Flowpack\SingleSignOn\Client\Security\SingleSignOnProvider
#               providerOptions:
#                 server: DemoServer
#                 globalSessionTouchInterval: 60
#               entryPoint: Flowpack\SingleSignOn\Client\Security\EntryPoint\SingleSignOnRedirect
#               entryPointOptions:
#                 server: DemoServer
Neos:
  Flow:
    security:
      firewall:
        filters:
          ssoClientSignedRequests:
            patternType: Flowpack\SingleSignOn\Client\Security\RequestPattern\ConjunctionPattern
            patternValue:
              patterns:
                -
                  patternType: ControllerObjectName
                  patternValue: Flowpack\SingleSignOn\Client\Controller\SessionController
                -
                  patternType: Flowpack\SingleSignOn\Client\Security\RequestPattern\SignedRequestPattern
                  patternValue:
                    resolverType: Flowpack\SingleSignOn\Client\Security\RequestPattern\SsoServerPublicKeyResolver
            interceptor: AccessDeny
    object:
      excludeClasses:
        mockery.mockery:
          - '.*'
