#
# Default Settings for Flowpack.SingleSignOn.Client
#

Flowpack:
  SingleSignOn:
    Client:
      client:
        serviceBaseUri: ''
        publicKeyFingerprint: ''
      server: null
      accountMapper:
        typeMapping: {  }
      log:
        logFailedSignedRequests: false
Neos:
  Flow:
    security:
      firewall:
        filters:
          ssoClientSignedRequests:
            patternType: Flowpack\SingleSignOn\Client\Security\RequestPattern\ConjunctionPattern
            patternValue:
              patterns:
                -
                  patternType: ControllerObjectName
                  patternValue: Flowpack\SingleSignOn\Client\Controller\SessionController
                -
                  patternType: Flowpack\SingleSignOn\Client\Security\RequestPattern\SignedRequestPattern
                  patternValue:
                    resolverType: Flowpack\SingleSignOn\Client\Security\RequestPattern\SsoServerPublicKeyResolver
            interceptor: AccessDeny
    object:
      excludeClasses:
        mockery.mockery:
          - '.*'
